### ISSUE TITLE
Crash on clicking Issues after installing Easy_Agile

### ISSUE THREAD

**Issue by pauleil** [SphereSoftware/easy_agile#21]
After installing Easy Agile (RM 1.1.2, Postgres), I can access the plugin tab with no problem.

However clicking Issues produces:

Processing IssuesController#index (for 192.168.1.2 at 2011-04-07 12:03:25) [GET]
  Parameters: {"project_id"=>"myproject", "action"=>"index", "controller"=>"issues"}

NoMethodError (undefined method `trackers' for #<Class:0x2ba6a72c>):
  app/helpers/queries_helper.rb:85:in`retrieve_query'
  app/controllers/issues_controller.rb:65:in `index'
  passenger (3.0.6) lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  passenger (3.0.6) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.6) lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  passenger (3.0.6) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.6) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`send'
  passenger (3.0.6) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  passenger (3.0.6) lib/phusion_passenger/utils.rb:479:in`safe_fork'
  passenger (3.0.6) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:357:in`**send**'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.6) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  passenger (3.0.6) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  passenger (3.0.6) lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  passenger (3.0.6) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  passenger (3.0.6) lib/phusion_passenger/abstract_server_collection.rb:82:in`synchronize'
  passenger (3.0.6) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.6) lib/phusion_passenger/spawn_manager.rb:213:in`spawn_rails_application'
  passenger (3.0.6) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.6) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.6) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.6) helper-scripts/passenger-spawn-server:99

Rendering /usr/local/www/redmine/public/500.html (500 Internal Server Error)

**Comment by rickyah** [comment]
I ran into this issue too with a similar error dump.

**Comment by msorc** [comment]
Thanks for reports, please provide the following info:
Have you created stories, iterations? What kind of?
How many issues do you have in the project? Have you created custom trackers or queries?
Thanks.

**Comment by pauleil** [comment]
Didn't create any stories - the error starts appearing immediately after the plugin is installed. I have close to 1,000 issues.

**Comment by rickyah** [comment]
Didn't create any stories, I have about 950 issues, 3 custom queries, and 5 trackers named
Epic
Story
Task
Bug
Support
