### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by marmotteinoz** [SphereSoftware/easy_agile#23]
Dear all.

I still can't get the easy agile plugin to work, after three full re-install step by step.
There are others (closed) similar tickets here, but I have checked all answers to them, i.e. re-installed gruff, nested_layouts etc...
Any help welcome..

See below:

 Processing EasyAgileController#show (for 192.168.0.112 at 2011-07-12 13:24:54) [GET]
  Parameters: {"project_id"=>"admin-test", "action"=>"show", "controller"=>"easy_agile"}

NoMethodError (undefined method `stories' for #<Project:0xb663165c>):
  /usr/lib/ruby/1.8/active_record/attribute_methods.rb:260:in`method_missing'
  vendor/plugins/easy_agile/app/controllers/easy_agile_controller.rb:7:in `show'
  /usr/lib/ruby/1.8/action_controller/base.rb:1331:in`send'
  /usr/lib/ruby/1.8/action_controller/base.rb:1331:in `perform_action_without_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:617:in`call_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:610:in `perform_action_without_benchmark'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/rescue.rb:160:in`perform_action_without_flash'
  /usr/lib/ruby/1.8/action_controller/flash.rb:146:in `perform_action'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in`send'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in `process_without_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:606:in`process'
  /usr/lib/ruby/1.8/action_controller/base.rb:391:in `process'
  /usr/lib/ruby/1.8/action_controller/base.rb:386:in`call'
  /usr/lib/ruby/1.8/action_controller/routing/route_set.rb:437:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:87:in`dispatch'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:121:in `_call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:130:in`build_middleware_stack'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in`call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:9:in`cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:28:in `call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/connection_pool.rb:361:in`call'
  /usr/lib/ruby/1.8/action_controller/string_coercion.rb:25:in `call'
  /usr/lib/ruby/1.8/rack/head.rb:9:in`call'
  /usr/lib/ruby/1.8/rack/methodoverride.rb:24:in `call'
  /usr/lib/ruby/1.8/action_controller/params_parser.rb:15:in`call'
  /usr/lib/ruby/1.8/action_controller/session/cookie_store.rb:93:in `call'
  /usr/lib/ruby/1.8/action_controller/failsafe.rb:26:in`call'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in `call'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in`synchronize'
  /usr/lib/ruby/1.8/rack/lock.rb:11:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:106:in`call'
  /usr/lib/ruby/1.8/rack/urlmap.rb:47:in `call'
  /usr/lib/ruby/1.8/rack/urlmap.rb:41:in`each'
  /usr/lib/ruby/1.8/rack/urlmap.rb:41:in `call'
  /usr/lib/ruby/1.8/rack/content_length.rb:13:in`call'
  /usr/lib/ruby/1.8/rack/handler/webrick.rb:48:in `service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
  /usr/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  /usr/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
  /usr/lib/ruby/1.8/webrick/server.rb:95:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in`each'
  /usr/lib/ruby/1.8/webrick/server.rb:92:in `start'
  /usr/lib/ruby/1.8/webrick/server.rb:23:in`start'
  /usr/lib/ruby/1.8/webrick/server.rb:82:in `start'
  /usr/lib/ruby/1.8/rack/handler/webrick.rb:14:in`run'

Rendering /usr/share/redmine/public/500.html (500 Internal Server Error)

**Comment by marmotteinoz** [comment]
Similar to issue#21..sorry for double-posting...I am new here :-/
