### ISSUE TITLE
undefined method `inside_layout' in layouts/ea_base.html.erb

### ISSUE THREAD

**Issue by mikebevz** [SphereSoftware/easy_agile#24]
Redmine 1.2.1.stable (MySQL)
RMagick available (optional)

When I'm trying to reach /projects/myproject/easy_agile I've got the following error

ActionView::TemplateError (undefined method `inside_layout' for #ActionView::Base:0xca762f8) on line #1 of vendor/plugins/easy_agile/app/views/layouts/ea_base.html.erb:
1: <% inside_layout 'base' do -%>
2: <% content_for :header_tags do %>
3: <%= stylesheet_link_tag(
4:                         'story/layout',

```
vendor/plugins/easy_agile/app/views/layouts/ea_base.html.erb:1
vendor/plugins/easy_agile/app/controllers/easy_agile_controller.rb:8:in `show'
passenger (3.0.7) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.7) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.7) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.7) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.7) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.7) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.7) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.7) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.7) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.7) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.7) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.7) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.7) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.7) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.7) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.7) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.7) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.7) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.7) helper-scripts/passenger-spawn-server:99
```

Let me know if I can help you with more info to fix this.

Thanks!

**Comment by msorc** [comment]
Have you installed nested_layouts? See Readme for details.

**Comment by mikebevz** [comment]
First off, I don't see nested_layouts in the Readme.
Anyway, after I've installed it and restarted the app the error persists.

**Comment by jomb** [comment]
Same problem for me

**Comment by msorc** [comment]
Have you done this (written on the project start page in README.rdoc file)?
./script/plugin install git://github.com/jwigal/nested_layouts.git
